import { CAF } from "../data/caf";

export function generateWordDoc(assessment) {
  const { meta, responses } = assessment;
  const orgSlug = (meta?.organisationName || "govassure")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const dateSlug = meta?.assessmentDate || new Date().toISOString().slice(0, 10);

  const sc = (s) => s === "achieved" ? "#00703c" : s === "partially_achieved" ? "#f47738" : s === "not_achieved" ? "#d4351c" : "#505a5f";
  const sl = (s) => s === "achieved" ? "Achieved" : s === "partially_achieved" ? "Partially achieved" : s === "not_achieved" ? "Not achieved" : "Not started";

  let body = `<h1 style="font-size:20pt;color:#0b0c0c;margin-bottom:4pt;">Govassure CAF v4.0 Assessment</h1>
    <table style="border-collapse:collapse;margin-bottom:16pt;">
      <tr><td style="padding:3pt 12pt 3pt 0;font-weight:bold;">Organisation</td><td>${meta?.organisationName || "—"}</td></tr>
      ${meta?.assessorName ? `<tr><td style="padding:3pt 12pt 3pt 0;font-weight:bold;">Assessor</td><td>${meta.assessorName}</td></tr>` : ""}
      <tr><td style="padding:3pt 12pt 3pt 0;font-weight:bold;">Date</td><td>${meta?.assessmentDate || "—"}</td></tr>
    </table>`;

  CAF.forEach((obj) => {
    body += `<h2 style="font-size:14pt;color:${obj.colour};border-bottom:2pt solid ${obj.colour};padding-bottom:4pt;margin-top:20pt;">Objective ${obj.id}: ${obj.title}</h2>
      <table style="border-collapse:collapse;width:100%;margin-bottom:12pt;font-size:10pt;"><thead><tr>
        <th style="background:${obj.colour};color:#fff;padding:5pt 8pt;text-align:left;width:40%;">Principle</th>
        <th style="background:${obj.colour};color:#fff;padding:5pt;text-align:center;">Achieved</th>
        <th style="background:${obj.colour};color:#fff;padding:5pt;text-align:center;">Partial</th>
        <th style="background:${obj.colour};color:#fff;padding:5pt;text-align:center;">Not achieved</th>
        <th style="background:${obj.colour};color:#fff;padding:5pt;text-align:center;">Not started</th>
        <th style="background:${obj.colour};color:#fff;padding:5pt;text-align:center;">Total</th>
      </tr></thead><tbody>`;
    obj.principles.forEach((p) => {
      const s = {a:0,pa:0,na:0,ns:0};
      p.igps.forEach((igp) => { const r=responses[igp.id]; if(!r?.score)s.ns++; else if(r.score==="achieved")s.a++; else if(r.score==="partially_achieved")s.pa++; else s.na++; });
      body += `<tr style="border-bottom:1pt solid #b1b4b6;">
        <td style="padding:5pt 8pt;">${p.id} – ${p.title}</td>
        <td style="padding:5pt;text-align:center;color:#00703c;font-weight:bold;">${s.a}</td>
        <td style="padding:5pt;text-align:center;color:#f47738;font-weight:${s.pa>0?"bold":"normal"};">${s.pa}</td>
        <td style="padding:5pt;text-align:center;color:#d4351c;font-weight:${s.na>0?"bold":"normal"};">${s.na}</td>
        <td style="padding:5pt;text-align:center;color:#505a5f;">${s.ns}</td>
        <td style="padding:5pt;text-align:center;font-weight:bold;">${p.igps.length}</td></tr>`;
    });
    body += `</tbody></table>`;
    obj.principles.forEach((p) => {
      body += `<h3 style="font-size:12pt;margin-top:14pt;margin-bottom:4pt;">${p.id} – ${p.title}</h3>
        <table style="border-collapse:collapse;width:100%;margin-bottom:12pt;font-size:9pt;"><thead><tr>
          <th style="background:#505a5f;color:#fff;padding:4pt 6pt;text-align:left;width:8%;">IGP</th>
          <th style="background:#505a5f;color:#fff;padding:4pt 6pt;text-align:left;width:22%;">Title</th>
          <th style="background:#505a5f;color:#fff;padding:4pt 6pt;text-align:left;width:18%;">Outcome</th>
          <th style="background:#505a5f;color:#fff;padding:4pt 6pt;text-align:left;">Evidence / Notes</th>
        </tr></thead><tbody>`;
      p.igps.forEach((igp) => {
        const r=responses[igp.id]; const score=r?.score||null;
        body += `<tr style="border-bottom:1pt solid #b1b4b6;">
          <td style="padding:4pt 6pt;font-weight:bold;">${igp.code}</td>
          <td style="padding:4pt 6pt;">${igp.title}</td>
          <td style="padding:4pt 6pt;color:${sc(score)};font-weight:${score?"bold":"normal"};">${sl(score)}</td>
          <td style="padding:4pt 6pt;color:#505a5f;">${r?.notes?r.notes.replace(/</g,"&lt;").replace(/>/g,"&gt;"):"—"}</td></tr>`;
      });
      body += `</tbody></table>`;
    });
  });

  const html = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Govassure CAF Assessment</title><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:2cm;}p{margin:4pt 0;}</style></head><body>${body}<p style="color:#505a5f;font-size:8pt;margin-top:24pt;border-top:1pt solid #b1b4b6;padding-top:6pt;">Generated by Govassure — govassure.uk — ${new Date().toLocaleDateString("en-GB")}.<br>This is a self-assessment only. Not an official NCSC assessment.</p></body></html>`;

  const blob = new Blob(["﻿", html], { type: "application/msword" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `govassure-caf-${orgSlug}-${dateSlug}.doc`;
  a.click();
  URL.revokeObjectURL(url);
}
